# Generated by Django 2.2.4 on 2019-08-26 13:30

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0001_d26081905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('mobile', models.IntegerField()),
                ('img', models.ImageField(blank=True, default=None, null=True, upload_to='GuidePhoto')),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('user_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.UserDetail')),
            ],
        ),
        migrations.CreateModel(
            name='GuideBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_from', models.DateField()),
                ('book_to', models.DateField()),
                ('total_rent', models.FloatField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.City')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.UserDetail')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.Guide')),
            ],
        ),
        migrations.CreateModel(
            name='GuideAvailable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avail_from', models.DateField()),
                ('avail_to', models.DateField()),
                ('rent_per_day', models.FloatField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.City')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.Guide')),
            ],
        ),
        migrations.AddConstraint(
            model_name='guidebooking',
            constraint=models.UniqueConstraint(fields=('guide', 'book_from'), name='uc1'),
        ),
        migrations.AddConstraint(
            model_name='guidebooking',
            constraint=models.UniqueConstraint(fields=('guide', 'book_to'), name='uc2'),
        ),
        migrations.AddConstraint(
            model_name='guidebooking',
            constraint=models.CheckConstraint(check=models.Q(total_rent__gte=0), name='positive total'),
        ),
        migrations.AddConstraint(
            model_name='guidebooking',
            constraint=models.CheckConstraint(check=models.Q(book_from__lte=django.db.models.expressions.F('book_to')), name='gb valid date span'),
        ),
        migrations.AddConstraint(
            model_name='guideavailable',
            constraint=models.UniqueConstraint(fields=('guide', 'avail_from'), name='unique from'),
        ),
        migrations.AddConstraint(
            model_name='guideavailable',
            constraint=models.UniqueConstraint(fields=('guide', 'avail_to'), name='unique to'),
        ),
        migrations.AddConstraint(
            model_name='guideavailable',
            constraint=models.CheckConstraint(check=models.Q(rent_per_day__gte=0), name='positive rent'),
        ),
        migrations.AddConstraint(
            model_name='guideavailable',
            constraint=models.CheckConstraint(check=models.Q(avail_from__lte=django.db.models.expressions.F('avail_to')), name='valid date span'),
        ),
        migrations.AddConstraint(
            model_name='guide',
            constraint=models.UniqueConstraint(fields=('user_detail', 'name'), name='users unique guide'),
        ),
        migrations.AddConstraint(
            model_name='guide',
            constraint=models.UniqueConstraint(fields=('mobile',), name='guides unique mobile'),
        ),
    ]
