# Generated by Django 2.2.4 on 2019-08-24 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0001_d24081913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('user_detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='homepage.UserDetail')),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GuideBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_from', models.DateField()),
                ('book_to', models.DateField()),
                ('total_rent', models.FloatField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.City')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.UserDetail')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.Guide')),
            ],
        ),
        migrations.CreateModel(
            name='GuideAvailable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avail_from', models.DateField()),
                ('avail_to', models.DateField()),
                ('rent_per_day', models.FloatField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.City')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.Guide')),
            ],
        ),
        migrations.AddConstraint(
            model_name='guidebooking',
            constraint=models.UniqueConstraint(fields=('guide', 'book_from'), name='uc1'),
        ),
        migrations.AddConstraint(
            model_name='guidebooking',
            constraint=models.UniqueConstraint(fields=('guide', 'book_to'), name='uc2'),
        ),
        migrations.AddConstraint(
            model_name='guidebooking',
            constraint=models.CheckConstraint(check=models.Q(total_rent__gte=0), name='positive total'),
        ),
        migrations.AddConstraint(
            model_name='guideavailable',
            constraint=models.UniqueConstraint(fields=('guide', 'avail_from'), name='unique from'),
        ),
        migrations.AddConstraint(
            model_name='guideavailable',
            constraint=models.UniqueConstraint(fields=('guide', 'avail_to'), name='unique to'),
        ),
        migrations.AddConstraint(
            model_name='guideavailable',
            constraint=models.CheckConstraint(check=models.Q(rent_per_day__gte=0), name='positive rent'),
        ),
    ]
