# Generated by Django 2.2.4 on 2019-08-26 18:57

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0001_d27081901'),
        ('guide', '0001_d27081901'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidebooking',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.City'),
        ),
        migrations.AddField(
            model_name='guidebooking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.UserDetail'),
        ),
        migrations.AddField(
            model_name='guidebooking',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.Guide'),
        ),
        migrations.AddField(
            model_name='guideavailable',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.City'),
        ),
        migrations.AddField(
            model_name='guideavailable',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.Guide'),
        ),
        migrations.AddField(
            model_name='guide',
            name='user_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.UserDetail'),
        ),
        migrations.AddConstraint(
            model_name='guidebooking',
            constraint=models.UniqueConstraint(fields=('guide', 'book_from'), name='uc1'),
        ),
        migrations.AddConstraint(
            model_name='guidebooking',
            constraint=models.UniqueConstraint(fields=('guide', 'book_to'), name='uc2'),
        ),
        migrations.AddConstraint(
            model_name='guidebooking',
            constraint=models.CheckConstraint(check=models.Q(total_rent__gte=0), name='positive total'),
        ),
        migrations.AddConstraint(
            model_name='guidebooking',
            constraint=models.CheckConstraint(check=models.Q(book_from__lte=django.db.models.expressions.F('book_to')), name='gb valid date span'),
        ),
        migrations.AddConstraint(
            model_name='guideavailable',
            constraint=models.UniqueConstraint(fields=('guide', 'avail_from'), name='unique from'),
        ),
        migrations.AddConstraint(
            model_name='guideavailable',
            constraint=models.UniqueConstraint(fields=('guide', 'avail_to'), name='unique to'),
        ),
        migrations.AddConstraint(
            model_name='guideavailable',
            constraint=models.CheckConstraint(check=models.Q(rent_per_day__gte=0), name='positive rent'),
        ),
        migrations.AddConstraint(
            model_name='guideavailable',
            constraint=models.CheckConstraint(check=models.Q(avail_from__lte=django.db.models.expressions.F('avail_to')), name='valid date span'),
        ),
        migrations.AddConstraint(
            model_name='guide',
            constraint=models.UniqueConstraint(fields=('user_detail', 'name'), name='users unique guide'),
        ),
        migrations.AddConstraint(
            model_name='guide',
            constraint=models.UniqueConstraint(fields=('mobile',), name='guides unique mobile'),
        ),
    ]
