# Generated by Django 2.2.6 on 2019-10-31 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_d18101902'),
        ('guide', '0002_d27081901'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='guide',
            name='users unique guide',
        ),
        migrations.RemoveConstraint(
            model_name='guide',
            name='guides unique mobile',
        ),
        migrations.RemoveConstraint(
            model_name='guideavailable',
            name='unique from',
        ),
        migrations.RemoveConstraint(
            model_name='guideavailable',
            name='unique to',
        ),
        migrations.RemoveConstraint(
            model_name='guideavailable',
            name='positive rent',
        ),
        migrations.RemoveConstraint(
            model_name='guideavailable',
            name='valid date span',
        ),
        migrations.RemoveConstraint(
            model_name='guidebooking',
            name='uc1',
        ),
        migrations.RemoveConstraint(
            model_name='guidebooking',
            name='uc2',
        ),
        migrations.RemoveConstraint(
            model_name='guidebooking',
            name='positive total',
        ),
        migrations.RemoveConstraint(
            model_name='guidebooking',
            name='gb valid date span',
        ),
        migrations.AddField(
            model_name='guide',
            name='city',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guide', to='homepage.City'),
        ),
        migrations.AddField(
            model_name='guide',
            name='code_name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='guide',
            name='country',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guide', to='homepage.Country'),
        ),
    ]
