# Generated by Django 2.2.6 on 2019-11-01 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0003_d31101901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guideavailable',
            name='city',
        ),
        migrations.RemoveField(
            model_name='guideavailable',
            name='rent_per_day',
        ),
        migrations.RemoveField(
            model_name='guidebooking',
            name='city',
        ),
    ]
