# Generated by Django 2.2.6 on 2019-11-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0004_d01111903'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidebooking',
            name='booking_time',
            field=models.DateTimeField(null=True),
        ),
    ]
