# Generated by Django 2.2.6 on 2019-11-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0006_d0111915'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='rent',
            field=models.FloatField(null=True),
        ),
    ]
