# Generated by Django 2.2.6 on 2019-11-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0007_d0111918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='code_name',
        ),
        migrations.AlterField(
            model_name='guide',
            name='name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
