# Generated by Django 2.2.4 on 2019-08-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_d26081923'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='topic',
            field=models.ManyToManyField(to='blog.Topic'),
        ),
    ]
