# Generated by Django 2.2.6 on 2019-10-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_d2910191'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='user_detail',
        ),
        migrations.AddField(
            model_name='comment',
            name='approve_comment',
            field=models.BooleanField(default=False),
        ),
    ]
