# Generated by Django 2.2.6 on 2019-11-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_d28101918'),
        ('blog', '0006_auto_20191107_0459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='homepage.UserDetail'),
        ),
        migrations.DeleteModel(
            name='Preference',
        ),
    ]
