# Generated by Django 2.2.6 on 2019-11-09 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20191109_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='user_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.UserDetail'),
        ),
    ]
