# Generated by Django 2.2.6 on 2019-11-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20191109_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='display_pic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='blog_pics'),
        ),
    ]
