# Generated by Django 2.2.4 on 2019-08-31 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_d27081901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='city',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.City'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='mobile',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
