# Generated by Django 2.2.5 on 2019-09-21 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_d31081901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('Space', 'Space'), ('Food', 'Food'), ('Guide', 'Guide')], max_length=20)),
                ('item_id', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('from_date', models.DateField(blank=True, default=None, null=True)),
                ('to_date', models.DateField(blank=True, default=None, null=True)),
                ('price', models.FloatField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.UserDetail')),
            ],
            options={
                'ordering': ['owner'],
            },
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.CheckConstraint(check=models.Q(price__gte=0), name='non-negative cart_item price'),
        ),
    ]
