# Generated by Django 2.2.5 on 2019-09-21 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_d22091901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='city',
            name='unique city',
        ),
        migrations.RemoveField(
            model_name='city',
            name='district',
        ),
        migrations.RemoveField(
            model_name='city',
            name='state',
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Country'),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('country', 'city'), name='unique city'),
        ),
    ]
