# Generated by Django 2.2.5 on 2019-10-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_d08101901'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='country',
            constraint=models.UniqueConstraint(fields=('name',), name='Unique Country'),
        ),
    ]
