# Generated by Django 2.2.4 on 2019-08-24 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0001_d24081913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.ImageField(blank=True, null=True, upload_to='FoodPhoto')),
                ('price', models.FloatField()),
                ('person', models.PositiveIntegerField(default=1)),
                ('available_at_time', models.CharField(choices=[('b', 'Breakfast'), ('l', 'Lunch'), ('d', 'Dinner'), ('a', 'all time')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantOwner',
            fields=[
                ('user_detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='homepage.UserDetail')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('mobile', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('img', models.ImageField(blank=True, null=True, upload_to='RestaurantPhoto')),
                ('open_from_day', models.CharField(choices=[('mo', 'Monday'), ('tu', 'Tuesday'), ('we', 'Wednesday'), ('th', 'Thursday'), ('fr', 'Friday'), ('sa', 'Saturday'), ('su', 'Sunday')], max_length=2)),
                ('open_to_day', models.CharField(choices=[('mo', 'Monday'), ('tu', 'Tuesday'), ('we', 'Wednesday'), ('th', 'Thursday'), ('fr', 'Friday'), ('sa', 'Saturday'), ('su', 'Sunday')], max_length=2)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.City')),
                ('restaurant_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.RestaurantOwner')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField()),
                ('order_time', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.UserDetail')),
            ],
            options={
                'ordering': ['-order_time', 'customer'],
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Food')),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Orders')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant'),
        ),
        migrations.AddConstraint(
            model_name='restaurant',
            constraint=models.UniqueConstraint(fields=('name', 'city'), name='unique restaurant in city'),
        ),
        migrations.AddConstraint(
            model_name='orders',
            constraint=models.UniqueConstraint(fields=('customer', 'order_time'), name='order primary constraint'),
        ),
        migrations.AddConstraint(
            model_name='orderdetail',
            constraint=models.UniqueConstraint(fields=('orders', 'food'), name='order has unique food'),
        ),
        migrations.AddConstraint(
            model_name='food',
            constraint=models.UniqueConstraint(fields=('restaurant', 'name'), name='unique food in restaurant'),
        ),
        migrations.AddConstraint(
            model_name='food',
            constraint=models.CheckConstraint(check=models.Q(price__gte=0), name='non-negative food price'),
        ),
    ]
