# Generated by Django 2.2.4 on 2019-09-04 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_d31081901'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='restaurant',
            name="user's unique restaurant in city",
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='user_detail',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to='homepage.UserDetail'),
        ),
        migrations.AddConstraint(
            model_name='restaurant',
            constraint=models.UniqueConstraint(fields=('user_detail', 'name'), name="user's unique restaurant"),
        ),
    ]
