# Generated by Django 2.2.4 on 2019-09-05 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_d04091901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['restaurant']},
        ),
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'ordering': ['orders']},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['user_detail']},
        ),
    ]
