# Generated by Django 2.2.6 on 2019-10-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_d22091912'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='food',
            name='unique food in restaurant',
        ),
        migrations.RemoveConstraint(
            model_name='food',
            name='non-negative food price',
        ),
        migrations.RemoveConstraint(
            model_name='restaurant',
            name="user's unique restaurant",
        ),
        migrations.AddField(
            model_name='food',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
