# Generated by Django 2.2.6 on 2019-10-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_d25101901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='available_at_time',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('All Time', 'All Time')], max_length=255),
        ),
    ]
