# Generated by Django 2.2.6 on 2019-10-27 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0007_d25101902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.FloatField(default=None, null=True)),
            ],
            options={
                'ordering': ['owner'],
            },
        ),
        migrations.CreateModel(
            name='CartDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='orderdetail',
            name='order has unique food',
        ),
        migrations.RemoveConstraint(
            model_name='orders',
            name='order primary constraint',
        ),
        migrations.AddField(
            model_name='cartdetail',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Cart'),
        ),
        migrations.AddField(
            model_name='cartdetail',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Food'),
        ),
        migrations.AddField(
            model_name='cart',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cart',
            name='restaurant',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant'),
        ),
    ]
