# Generated by Django 2.2.4 on 2019-08-24 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0001_d24081913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('mobile', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('img', models.ImageField(blank=True, default=None, null=True, upload_to='ResidencePhoto')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.City')),
            ],
        ),
        migrations.CreateModel(
            name='ResidenceOwner',
            fields=[
                ('user_detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='homepage.UserDetail')),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('rent', models.FloatField(default=0)),
                ('person', models.PositiveIntegerField(default=1)),
                ('shared', models.BooleanField(default=False)),
                ('img', models.ImageField(blank=True, default=None, null=True, upload_to='ResidenceSpacePhoto')),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residence.Residence')),
            ],
        ),
        migrations.CreateModel(
            name='SpaceBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_from', models.DateField()),
                ('book_to', models.DateField()),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.UserDetail')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residence.Space')),
            ],
        ),
        migrations.CreateModel(
            name='SpaceAvailable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avail_from', models.DateField()),
                ('avail_to', models.DateField()),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residence.Space')),
            ],
        ),
        migrations.AddField(
            model_name='residence',
            name='residence_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residence.ResidenceOwner'),
        ),
        migrations.AddConstraint(
            model_name='spacebooking',
            constraint=models.UniqueConstraint(fields=('space', 'book_from'), name='SpaceBooking unq from'),
        ),
        migrations.AddConstraint(
            model_name='spacebooking',
            constraint=models.UniqueConstraint(fields=('space', 'book_to'), name='SpaceBooking unq to'),
        ),
        migrations.AddConstraint(
            model_name='spaceavailable',
            constraint=models.UniqueConstraint(fields=('space', 'avail_from'), name='Space avail unique from'),
        ),
        migrations.AddConstraint(
            model_name='spaceavailable',
            constraint=models.UniqueConstraint(fields=('space', 'avail_to'), name='Space avail unique to'),
        ),
        migrations.AddConstraint(
            model_name='space',
            constraint=models.UniqueConstraint(fields=('residence', 'space_name'), name="residence's unique place"),
        ),
        migrations.AddConstraint(
            model_name='space',
            constraint=models.CheckConstraint(check=models.Q(rent__gte=0), name='non-negative rent'),
        ),
        migrations.AddConstraint(
            model_name='residence',
            constraint=models.UniqueConstraint(fields=('name', 'city'), name='unique residence in city'),
        ),
    ]
