# Generated by Django 2.2.5 on 2019-10-17 18:57

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0006_d18101902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.IntegerField(blank=True, default=None, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('img', models.ImageField(blank=True, default=None, null=True, upload_to='ResidencePhoto')),
                ('city', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.City')),
                ('country', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.Country')),
                ('user_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.UserDetail')),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residence.Residence')),
            ],
        ),
        migrations.CreateModel(
            name='SpaceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haha', models.CharField(max_length=10, null=True)),
                ('haha2', models.CharField(max_length=10, null=True)),
                ('name', models.CharField(max_length=255)),
                ('person', models.PositiveIntegerField()),
                ('rent', models.FloatField()),
                ('pic', models.ImageField(upload_to='SpaceTypePhoto')),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residence.Residence')),
            ],
        ),
        migrations.CreateModel(
            name='SpaceBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_time', models.DateTimeField()),
                ('total_rent', models.FloatField()),
                ('book_from', models.DateField()),
                ('book_to', models.DateField()),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.UserDetail')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residence.Space')),
            ],
            options={
                'ordering': ['-booking_time'],
            },
        ),
        migrations.CreateModel(
            name='SpaceAvailable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avail_from', models.DateField()),
                ('avail_to', models.DateField()),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residence.Space')),
            ],
            options={
                'ordering': ['avail_from', '-avail_to'],
            },
        ),
        migrations.AddField(
            model_name='space',
            name='space_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='residence.SpaceType'),
        ),
        migrations.AddConstraint(
            model_name='spacebooking',
            constraint=models.UniqueConstraint(fields=('space', 'book_from'), name='SpaceBooking unq from'),
        ),
        migrations.AddConstraint(
            model_name='spacebooking',
            constraint=models.UniqueConstraint(fields=('space', 'book_to'), name='SpaceBooking unq to'),
        ),
        migrations.AddConstraint(
            model_name='spacebooking',
            constraint=models.CheckConstraint(check=models.Q(book_from__lte=django.db.models.expressions.F('book_to')), name='sb unique time span'),
        ),
        migrations.AddConstraint(
            model_name='spacebooking',
            constraint=models.CheckConstraint(check=models.Q(total_rent__gte=0), name='sb non-negative total rent'),
        ),
    ]
