# Generated by Django 2.2.5 on 2019-09-23 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_d22091902'),
        ('residence', '0001_d12091923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residence',
            name='address',
        ),
        migrations.AddField(
            model_name='residence',
            name='country',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.Country'),
        ),
        migrations.AlterField(
            model_name='residence',
            name='city',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.City'),
        ),
    ]
