# Generated by Django 2.2.6 on 2019-10-24 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residence', '0001_d24101902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spaceavailable',
            options={'ordering': ['space', 'avail_from']},
        ),
    ]
