# Generated by Django 2.2.5 on 2019-10-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residence', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spacetype',
            name='haha',
        ),
        migrations.RemoveField(
            model_name='spacetype',
            name='haha2',
        ),
        migrations.AlterField(
            model_name='spacetype',
            name='pic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='SpaceTypePhoto'),
        ),
    ]
