# Generated by Django 2.2.5 on 2019-10-07 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residence', '0002_d23091901'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='spaceavailable',
            name='Space avail unique from',
        ),
        migrations.RemoveConstraint(
            model_name='spaceavailable',
            name='Space avail unique to',
        ),
    ]
