# Generated by Django 2.2.5 on 2019-10-12 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residence', '0003_d08101901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spaceavailable',
            name='number_of_space',
        ),
        migrations.RemoveField(
            model_name='spacebooking',
            name='number_of_space',
        ),
    ]
