# Generated by Django 2.2.5 on 2019-10-16 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residence', '0004_d20101901'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('person', models.PositiveIntegerField()),
                ('rent', models.FloatField()),
                ('pic', models.ImageField(upload_to='SpaceTypePhoto')),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='space',
            name="residence's unique space",
        ),
        migrations.RemoveConstraint(
            model_name='space',
            name='non-negative rent',
        ),
        migrations.RemoveConstraint(
            model_name='spaceavailable',
            name='sa valid date span ',
        ),
        migrations.RemoveField(
            model_name='space',
            name='description',
        ),
        migrations.RemoveField(
            model_name='space',
            name='img',
        ),
        migrations.RemoveField(
            model_name='space',
            name='person',
        ),
        migrations.RemoveField(
            model_name='space',
            name='rent',
        ),
        migrations.RemoveField(
            model_name='space',
            name='shared',
        ),
        migrations.RemoveField(
            model_name='space',
            name='space_type_name',
        ),
        migrations.AddField(
            model_name='spacetype',
            name='residence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residence.Residence'),
        ),
        migrations.AddField(
            model_name='space',
            name='space_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='residence.SpaceType'),
        ),
    ]
